
spring:
  config:
    activate:
      on-profile: dev
  #kafka:
   # producer:
    #  bootstrap-servers: localhost:9092
     # key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      #value-serializer: org.apache.kafka.common.serialization.StringSerializer
    #consumer:
     # bootstrap-servers: localhost:9092
      #key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      #value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      #group-id: library-event-listener-group
    #admin:
     # properties:
      #  bootstrap.servers: localhost:9092
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
  h2:
    console:
      enabled: true
resilience4j:
  ratelimiter:
    configs:
      default:
        limitForPeriod: 1
        limitRefreshPeriod: 60s
        timeoutDuration: 20s
  instances:
    test:
      baseConfig: default
